export const Currencies = [
    { value: "USD", label: "$ Dollar", locale: "en-US" },
    { value: "KES", label: "KSh Kenyan Shilling", locale: "sw-KE" },
    { value: "EUR", label: "€ Euro", locale: "de-DE" },
    { value: "JPY", label: "¥ Yen", locale: "ja-JP" },
    { value: "GBP", label: "£ Pound", locale: "en-GB" },
    { value: "AUD", label: "A$ Australian Dollar", locale: "en-AU" },
    { value: "CAD", label: "C$ Canadian Dollar", locale: "en-CA" },
    { value: "CHF", label: "CHF Swiss Franc", locale: "de-CH" },
    { value: "CNY", label: "¥ Chinese Yuan", locale: "zh-CN" },
    { value: "SEK", label: "kr Swedish Krona", locale: "sv-SE" },
    { value: "NZD", label: "NZ$ New Zealand Dollar", locale: "en-NZ" },
    { value: "MXN", label: "Mex$ Mexican Peso", locale: "es-MX" },
    { value: "SGD", label: "S$ Singapore Dollar", locale: "en-SG" },
    { value: "HKD", label: "HK$ Hong Kong Dollar", locale: "zh-HK" },
    { value: "NOK", label: "kr Norwegian Krone", locale: "no-NO" },
    { value: "INR", label: "₹ Indian Rupee", locale: "hi-IN" },
    { value: "RUB", label: "₽ Russian Ruble", locale: "ru-RU" },
    { value: "ZAR", label: "R South African Rand", locale: "en-ZA" },
    { value: "TRY", label: "₺ Turkish Lira", locale: "tr-TR" },
    { value: "BRL", label: "R$ Brazilian Real", locale: "pt-BR" },
    { value: "KRW", label: "₩ South Korean Won", locale: "ko-KR" },
    { value: "MYR", label: "RM Malaysian Ringgit", locale: "ms-MY" },
    { value: "IDR", label: "Rp Indonesian Rupiah", locale: "id-ID" },
    { value: "PHP", label: "₱ Philippine Peso", locale: "en-PH" },
    { value: "THB", label: "฿ Thai Baht", locale: "th-TH" },
    { value: "VND", label: "₫ Vietnamese Dong", locale: "vi-VN" },
    { value: "EGP", label: "E£ Egyptian Pound", locale: "ar-EG" },
    { value: "NGN", label: "₦ Nigerian Naira", locale: "en-NG" },
    { value: "DZD", label: "DA Algerian Dinar", locale: "ar-DZ" },
    { value: "MAD", label: "MAD Moroccan Dirham", locale: "ar-MA" },
    { value: "AOA", label: "Kz Angolan Kwanza", locale: "pt-AO" },
    { value: "GHS", label: "GH₵ Ghanaian Cedi", locale: "en-GH" },
    { value: "XAF", label: "FCFA Central African CFA franc", locale: "fr-CM" },
    { value: "XOF", label: "CFA West African CFA franc", locale: "fr-SN" },
    { value: "UGX", label: "USh Ugandan Shilling", locale: "en-UG" },
    { value: "TZS", label: "TSh Tanzanian Shilling", locale: "sw-TZ" },
    { value: "MZN", label: "MT Mozambican Metical", locale: "pt-MZ" },
    { value: "SAR", label: "SR Saudi Riyal", locale: "ar-SA" }

];

export type Currency = (typeof Currencies)[0];
